name: Simple workflow test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: contents of the directory 2
        run: ls -la
      - name: current path 2
        run: pwd
      - name: disk space
        run: df -h
      - name: kernel version 2
        run: uname -a
